In [2]:
import numpy as np
import sympy as sym

#define constants
t, g= sym.symbols('t g')
mc, mp = sym.symbols('m_c m_p')
L,fx = sym.symbols('L f_x ')

# define variables 
theta = sym.symbols(r'\theta')
# z_d = sym.symbols('z_d')
theta_d = sym.symbols(r'\theta_d')


In [3]:

theta_dd = 1/(L*(mc + mp*sym.sin(theta)**2))*(-fx*sym.cos(theta)-mp*L*(theta_d)**2*sym.cos(theta)*sym.sin(theta)-(mc+mp)*g*sym.sin(theta))

x_vec = sym.Matrix([theta,theta_d])
vector_field = sym.Matrix([theta_d, theta_dd])


In [4]:
vector_field

Matrix([
[                                                                                                                 \theta_d],
[(-L*\theta_d**2*m_p*sin(\theta)*cos(\theta) - f_x*cos(\theta) - g*(m_c + m_p)*sin(\theta))/(L*(m_c + m_p*sin(\theta)**2))]])

In [5]:
pfpx = vector_field.jacobian([theta,theta_d])
pfpu = vector_field.jacobian([fx])

# g = 9.81
# mc = 10
# mp = 1
# L =0.5

pfpx_f=sym.lambdify((g,fx,mc,mp,L,theta,theta_d), pfpx)

pfpu_f = sym.lambdify((g,fx,mc,mp,L,theta,theta_d), pfpu)
Ahat= pfpx_f(9.81,0,10,1,0.5,np.pi,0,)
Bhat = pfpu_f(9.81,0,10,1,0.5,np.pi,0,)

In [6]:
Ahat

array([[ 0.   ,  1.   ],
       [21.582, -0.   ]])

In [7]:
Bhat

array([[0. ],
       [0.2]])

In [8]:
import scipy.signal as sig
I = np.eye(2)
A = I + 0.005*Ahat
B = 0.005*Bhat
print(A)
print(B)

[[1.      0.005  ]
 [0.10791 1.     ]]
[[0.   ]
 [0.001]]


In [12]:
s_desired = np.array([-2+8j, -2-8j])
# s_desired = np.array([-2+1j, -2-1j])
z_desired = np.exp(s_desired*0.005)
cart_pole_gain = sig.place_poles(A, B, z_desired).gain_matrix
print(cart_pole_gain)

[[444.48486861  21.48420104]]
[0.9892579+0.03959143j 0.9892579-0.03959143j]
